---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Site Contents
- type: document
  path: content/_index.md
  label: Homepage
- type: directory
  path: content/posts
  label: Blog Posts
  create: documents
  match: "*"
  exclude: _index.md
- type: document
  path: content/about.md
  label: About
- type: document
  path: content/contact.md
  label: Contact
- type: heading
  label: Site Configurations
- type: document
  path: config/config.json
  label: Configuration
- type: document
  path: config/variables.json
  label: Variables
- type: document
  path: config/menu.json
  label: Menu
upload_dir: public/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
